[toolchain]
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
pow_protocol = "PoWgG9zPrzF2vFUQRTyU4L1aNMZmbsemxJgwhycjtS4"
pow_pool = "4DHpKjPiay8FiimQ4UFWnZY6tQVYwPXwiqu6445wwZif"
pow_privacy = "EnchaSHvRoShUp6zrF2awSeQGVYjGFZfjpkdoi2nKPBk"

[programs.localnet]
pow_pool = "Poo1111111111111111111111111111111111111111"
pow_privacy = "Priv111111111111111111111111111111111111111"
pow_protocol = "PoW1111111111111111111111111111111111111111"
transfer_hook = "Hook111111111111111111111111111111111111111"

[programs.mainnet]
pow_pool = "Poo1111111111111111111111111111111111111111"
pow_privacy = "Priv111111111111111111111111111111111111111"
pow_protocol = "PoW1111111111111111111111111111111111111111"
transfer_hook = "Hook111111111111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://devnet.helius-rpc.com/?api-key=f4718f33-4936-4c0b-b947-e079b805c3c8"
wallet = "keys/devnet-deployer.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "0.0.0.0"
url = "https://api.devnet.solana.com"
ledger = ".anchor/test-ledger"
rpc_port = 8899
