[package]
name = "encrypted-ixs"
version = "0.1.0"
description = "MPC circuits for privacy-preserving PoW mining"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
arcis = "0.7.0"
